name: 'Slack Post Message Action'
description: 'GitHub Action that posts a message to a Slack channel'
inputs:
  token:
    description: "The Slack auth token.  This is only required if environment variable SLACK_BOT_TOKEN is not set."
    required: false
  channel:
    description: "The channel name to post to"
    required: true
  thread_ts:
    description: "The timestamp ID of the parent message to reply to"
    required: false
  text:
    description: "The message text to post"
    required: true
outputs:
  ts:
    description: "The timestamp ID of the message that was just posted"
branding:
  icon: 'tag'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - run: |
        {
          echo "ts=<<EOF"
          curl --silent --show-error -X POST -H "Authorization: Bearer ${{ env.SLACK_BOT_TOKEN || inputs.token }}" -H "Content-Type: application/json" --url https://slack.com/api/chat.postMessage \
            -d "{\"channel\": \"${{ inputs.channel }}\", \"thread_ts\":\"${{ inputs.thread_ts }}\", \"text\":\"${{ inputs.text }}\"}" \
            | jq --raw-output '.ts'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
      shell: bash
