name: 'Slack Post Message Action'
description: 'GitHub Action that posts a message to a Slack channel'
inputs:
  token:
    description: "The Slack auth token.  This is only required if environment variable SLACK_BOT_TOKEN is not set."
    required: false
  channel:
    description: "The channel name to post to"
    required: true
  thread_ts:
    description: "The timestamp ID of the parent message to reply to"
    required: false
  text:
    description: "The message text to post"
    required: true
  unfurl_links:
    description: "Whether links in the message should be unfurled"
    type: boolean
    default: true
outputs:
  ts:
    description: "The timestamp ID of the message that was just posted"
branding:
  icon: 'tag'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        response=$(curl --fail-with-body --silent --show-error \
          --request POST \
          --header "Authorization: Bearer ${{ env.SLACK_BOT_TOKEN || inputs.token }}" \
          --header "Content-Type: application/json; charset=utf-8" \
          --url https://slack.com/api/chat.postMessage \
          --data "{\"channel\": \"${{ inputs.channel }}\", \"thread_ts\": \"${{ inputs.thread_ts }}\", \"unfurl_links\": ${{ inputs.unfurl_links }}, \"text\": \"${{ inputs.text }}\"}" \
        )
        echo "Slack API response:\n$response"
        {
          echo "ts<<EOF"
          echo "$response" | jq --raw-output '.ts'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
